name: Build and Push Saleor Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: docker build -t saleor .

    - name: Login to Amazon ECR
      run: |
        aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }}

    - name: Tag Docker Image
      run: docker tag saleor:latest ${{ secrets.ECR_URL }}/saleor:latest

    - name: Push to Amazon ECR
      run: docker push ${{ secrets.ECR_URL }}/saleor:latest
