apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: saleor-platform
  name: saleor-worker
  namespace: saleor
spec:
  selector:
    matchLabels:
      app: saleor-platform
  template:
    metadata:
      labels:
        app: saleor-platform
    spec:
      containers:
        - args:
            - -A
            - saleor
            - --app=saleor.celeryconf:app
            - worker
            - --loglevel=info
            - -B
          command:
            - celery
          env:
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: saleor-secrets-multiline
                  key: RSA_PRIVATE_KEY
          envFrom:
            - secretRef:
                name: saleor-secrets
          image: <ECR_PUBLIC_REGISTRY_URL>/saleor:<IMAGE_TAG>
          imagePullPolicy: Always
          name: saleor-worker
          resources:
            requests:
              cpu: 100m
              memory: 256M
      restartPolicy: Always
